// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file ankiweb.proto (package net.ankiweb, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ankiweb.proto.
 */
export const file_ankiweb: GenFile = /*@__PURE__*/
  fileDesc("Cg1hbmtpd2ViLnByb3RvEgtuZXQuYW5raXdlYiI3CgtBZGRvbkJyYW5jaBITCgttaW5fdmVyc2lvbhgBIAEoDRITCgttYXhfdmVyc2lvbhgCIAEoBSKiAQoJQWRkb25JbmZvEhUKCGFkZG9uX2lkGAEgASgNSACIAQESDQoFdGl0bGUYAiABKAkSDAoEdGFncxgDIAEoCRITCgtzdXBwb3J0X3VybBgEIAEoCRITCgtkZXNjcmlwdGlvbhgFIAEoCRIqCghicmFuY2hlcxgGIAMoCzIYLm5ldC5hbmtpd2ViLkFkZG9uQnJhbmNoQgsKCV9hZGRvbl9pZCJJCglBZGRvbkZpbGUSEAoIemlwX2RhdGEYASABKAwSGQoMYnJhbmNoX2luZGV4GAIgASgNSACIAQFCDwoNX2JyYW5jaF9pbmRleCJuChJVcGxvYWRBZGRvblJlcXVlc3QSJAoEaW5mbxgBIAEoCzIWLm5ldC5hbmtpd2ViLkFkZG9uSW5mbxIpCgRmaWxlGAIgASgLMhYubmV0LmFua2l3ZWIuQWRkb25GaWxlSACIAQFCBwoFX2ZpbGUiJwoTVXBsb2FkQWRkb25SZXNwb25zZRIQCghhZGRvbl9pZBgBIAEoDWIGcHJvdG8z");

/**
 * @generated from message net.ankiweb.AddonBranch
 */
export type AddonBranch = Message<"net.ankiweb.AddonBranch"> & {
  /**
   * @generated from field: uint32 min_version = 1;
   */
  minVersion: number;

  /**
   * @generated from field: int32 max_version = 2;
   */
  maxVersion: number;
};

/**
 * Describes the message net.ankiweb.AddonBranch.
 * Use `create(AddonBranchSchema)` to create a new message.
 */
export const AddonBranchSchema: GenMessage<AddonBranch> = /*@__PURE__*/
  messageDesc(file_ankiweb, 0);

/**
 * @generated from message net.ankiweb.AddonInfo
 */
export type AddonInfo = Message<"net.ankiweb.AddonInfo"> & {
  /**
   * @generated from field: optional uint32 addon_id = 1;
   */
  addonId?: number | undefined;

  /**
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * @generated from field: string tags = 3;
   */
  tags: string;

  /**
   * @generated from field: string support_url = 4;
   */
  supportUrl: string;

  /**
   * @generated from field: string description = 5;
   */
  description: string;

  /**
   * @generated from field: repeated net.ankiweb.AddonBranch branches = 6;
   */
  branches: AddonBranch[];
};

/**
 * Describes the message net.ankiweb.AddonInfo.
 * Use `create(AddonInfoSchema)` to create a new message.
 */
export const AddonInfoSchema: GenMessage<AddonInfo> = /*@__PURE__*/
  messageDesc(file_ankiweb, 1);

/**
 * @generated from message net.ankiweb.AddonFile
 */
export type AddonFile = Message<"net.ankiweb.AddonFile"> & {
  /**
   * @generated from field: bytes zip_data = 1;
   */
  zipData: Uint8Array;

  /**
   * @generated from field: optional uint32 branch_index = 2;
   */
  branchIndex?: number | undefined;
};

/**
 * Describes the message net.ankiweb.AddonFile.
 * Use `create(AddonFileSchema)` to create a new message.
 */
export const AddonFileSchema: GenMessage<AddonFile> = /*@__PURE__*/
  messageDesc(file_ankiweb, 2);

/**
 * @generated from message net.ankiweb.UploadAddonRequest
 */
export type UploadAddonRequest = Message<"net.ankiweb.UploadAddonRequest"> & {
  /**
   * @generated from field: net.ankiweb.AddonInfo info = 1;
   */
  info?: AddonInfo | undefined;

  /**
   * @generated from field: optional net.ankiweb.AddonFile file = 2;
   */
  file?: AddonFile | undefined;
};

/**
 * Describes the message net.ankiweb.UploadAddonRequest.
 * Use `create(UploadAddonRequestSchema)` to create a new message.
 */
export const UploadAddonRequestSchema: GenMessage<UploadAddonRequest> = /*@__PURE__*/
  messageDesc(file_ankiweb, 3);

/**
 * @generated from message net.ankiweb.UploadAddonResponse
 */
export type UploadAddonResponse = Message<"net.ankiweb.UploadAddonResponse"> & {
  /**
   * @generated from field: uint32 addon_id = 1;
   */
  addonId: number;
};

/**
 * Describes the message net.ankiweb.UploadAddonResponse.
 * Use `create(UploadAddonResponseSchema)` to create a new message.
 */
export const UploadAddonResponseSchema: GenMessage<UploadAddonResponse> = /*@__PURE__*/
  messageDesc(file_ankiweb, 4);

