// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file ankiweb.proto (package net.ankiweb, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ankiweb.proto.
 */
export const file_ankiweb: GenFile = /*@__PURE__*/
  fileDesc("Cg1hbmtpd2ViLnByb3RvEgtuZXQuYW5raXdlYiJhCgtBZGRvbkJyYW5jaBIYCgttaW5fdmVyc2lvbhgBIAEoDUgAiAEBEhgKC21heF92ZXJzaW9uGAIgASgFSAGIAQFCDgoMX21pbl92ZXJzaW9uQg4KDF9tYXhfdmVyc2lvbiLpAQoJQWRkb25JbmZvEhUKCGFkZG9uX2lkGAEgASgNSACIAQESEgoFdGl0bGUYAiABKAlIAYgBARIRCgR0YWdzGAMgASgJSAKIAQESGAoLc3VwcG9ydF91cmwYBCABKAlIA4gBARIYCgtkZXNjcmlwdGlvbhgFIAEoCUgEiAEBEioKCGJyYW5jaGVzGAYgAygLMhgubmV0LmFua2l3ZWIuQWRkb25CcmFuY2hCCwoJX2FkZG9uX2lkQggKBl90aXRsZUIHCgVfdGFnc0IOCgxfc3VwcG9ydF91cmxCDgoMX2Rlc2NyaXB0aW9uIlsKCUFkZG9uRmlsZRIVCgh6aXBfZGF0YRgBIAEoDEgAiAEBEhkKDGJyYW5jaF9pbmRleBgCIAEoDUgBiAEBQgsKCV96aXBfZGF0YUIPCg1fYnJhbmNoX2luZGV4InwKElVwbG9hZEFkZG9uUmVxdWVzdBIpCgRpbmZvGAEgASgLMhYubmV0LmFua2l3ZWIuQWRkb25JbmZvSACIAQESKQoEZmlsZRgCIAEoCzIWLm5ldC5hbmtpd2ViLkFkZG9uRmlsZUgBiAEBQgcKBV9pbmZvQgcKBV9maWxlIjkKE1VwbG9hZEFkZG9uUmVzcG9uc2USFQoIYWRkb25faWQYASABKA1IAIgBAUILCglfYWRkb25faWRiBnByb3RvMw");

/**
 * @generated from message net.ankiweb.AddonBranch
 */
export type AddonBranch = Message<"net.ankiweb.AddonBranch"> & {
  /**
   * @generated from field: optional uint32 min_version = 1;
   */
  minVersion?: number | undefined;

  /**
   * @generated from field: optional int32 max_version = 2;
   */
  maxVersion?: number | undefined;
};

/**
 * Describes the message net.ankiweb.AddonBranch.
 * Use `create(AddonBranchSchema)` to create a new message.
 */
export const AddonBranchSchema: GenMessage<AddonBranch> = /*@__PURE__*/
  messageDesc(file_ankiweb, 0);

/**
 * @generated from message net.ankiweb.AddonInfo
 */
export type AddonInfo = Message<"net.ankiweb.AddonInfo"> & {
  /**
   * @generated from field: optional uint32 addon_id = 1;
   */
  addonId?: number | undefined;

  /**
   * @generated from field: optional string title = 2;
   */
  title?: string | undefined;

  /**
   * @generated from field: optional string tags = 3;
   */
  tags?: string | undefined;

  /**
   * @generated from field: optional string support_url = 4;
   */
  supportUrl?: string | undefined;

  /**
   * @generated from field: optional string description = 5;
   */
  description?: string | undefined;

  /**
   * @generated from field: repeated net.ankiweb.AddonBranch branches = 6;
   */
  branches: AddonBranch[];
};

/**
 * Describes the message net.ankiweb.AddonInfo.
 * Use `create(AddonInfoSchema)` to create a new message.
 */
export const AddonInfoSchema: GenMessage<AddonInfo> = /*@__PURE__*/
  messageDesc(file_ankiweb, 1);

/**
 * @generated from message net.ankiweb.AddonFile
 */
export type AddonFile = Message<"net.ankiweb.AddonFile"> & {
  /**
   * @generated from field: optional bytes zip_data = 1;
   */
  zipData?: Uint8Array | undefined;

  /**
   * @generated from field: optional uint32 branch_index = 2;
   */
  branchIndex?: number | undefined;
};

/**
 * Describes the message net.ankiweb.AddonFile.
 * Use `create(AddonFileSchema)` to create a new message.
 */
export const AddonFileSchema: GenMessage<AddonFile> = /*@__PURE__*/
  messageDesc(file_ankiweb, 2);

/**
 * @generated from message net.ankiweb.UploadAddonRequest
 */
export type UploadAddonRequest = Message<"net.ankiweb.UploadAddonRequest"> & {
  /**
   * @generated from field: optional net.ankiweb.AddonInfo info = 1;
   */
  info?: AddonInfo | undefined;

  /**
   * @generated from field: optional net.ankiweb.AddonFile file = 2;
   */
  file?: AddonFile | undefined;
};

/**
 * Describes the message net.ankiweb.UploadAddonRequest.
 * Use `create(UploadAddonRequestSchema)` to create a new message.
 */
export const UploadAddonRequestSchema: GenMessage<UploadAddonRequest> = /*@__PURE__*/
  messageDesc(file_ankiweb, 3);

/**
 * @generated from message net.ankiweb.UploadAddonResponse
 */
export type UploadAddonResponse = Message<"net.ankiweb.UploadAddonResponse"> & {
  /**
   * @generated from field: optional uint32 addon_id = 1;
   */
  addonId?: number | undefined;
};

/**
 * Describes the message net.ankiweb.UploadAddonResponse.
 * Use `create(UploadAddonResponseSchema)` to create a new message.
 */
export const UploadAddonResponseSchema: GenMessage<UploadAddonResponse> = /*@__PURE__*/
  messageDesc(file_ankiweb, 4);

